---
- name: Teste de Instalação do nginx
  hosts: all
  remote_user: pauloaragao
  become: true
  tasks:
    - name: Instalar o nginx
      apt:
        name: nginx
        state: present
        update_cache: true
      register: nginx_out
    
    - name: Verificar a instalação do nginx
      debug:
        msg: " {{ nginx_out }} "
    
    - name: Ver a rede 
      debug:
        msg: "{{ ansible_eth0.ipv4.address }}"